In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# 示例数据
models = ["Tree_conv", "Transformer", "Tree_transformer"]
categories = ["Analysis", "Encoding", "Inference"]

data = {
    "Tree_conv": {
        "Analysis": 1.699415797899809e-05,
        "Encoding": 0.32585111174058884,
        "Inference": 0.011281246731840956
    },
    "Transformer": {
        "Analysis": 1.5631804619756436e-05,
        "Encoding": 0.18211924681502545,
        "Inference": 0.004838372474140837
    },
    "Tree_transformer": {
        "Analysis": 1.7068361274007607e-05,
        "Encoding": 0.3275578327122506,
        "Inference": 0.020449148399678294
    }
}

# 绘制柱状图
fig, ax = plt.subplots()

bar_width = 0.2
bar_positions = np.arange(len(models))

for i, category in enumerate(categories):
    values = [data[model][category] for model in models]
    ax.bar(bar_positions + i * bar_width, values, bar_width, label=category)

# 设置坐标轴标签和标题
ax.set_xticks(bar_positions + bar_width)
ax.set_xticklabels(models)
ax.set_yscale('log')  # 设置纵坐标为对数坐标
ax.set_ylabel('Log Scale')

# 添加图例
ax.legend()

plt.savefig('./bar_chart.svg', format='svg', bbox_inches='tight')
# 显示图形
plt.show()


In [ ]:
def format_scientific_notation(number):
    # 将科学计数法转为字符串
    str_number = "{:e}".format(number)
    # 分离有效数字和指数部分
    mantissa, exponent = str_number.split('e')
    # 将有效数字转为浮点数，以便进行格式化
    mantissa = 9.994 if float(mantissa) >= 9.995 else float(mantissa)
    # 限制有效位数为两位
    mantissa = format(mantissa, '.2f')
    # 将指数部分转为整数
    exponent = int(exponent)
    # 限制指数的范围在[-9, 9]之间
    exponent = max(-9, min(9, exponent))
    # 输出格式化后的结果
    result = "{},{},{:d}".format(mantissa, '1' if exponent >= 0 else '0', abs(exponent))
    return result

# 示例
number = 9.998
result = format_scientific_notation(number)
print(result)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pickle

# 生成示例数据


with open('./pg.txt','rb') as f:
    y1_values = pickle.load(f)
with open('./tf.txt','rb') as f:
    y2_values = pickle.load(f)

num_data_points = len(y1_values)
x_values = np.linspace(0, len(y1_values), len(y1_values))

# 绘制折线图
plt.plot(x_values, y1_values, label='pg')
plt.plot(x_values, y2_values, label='tf')

# 设置坐标轴标签和标题
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Line Chart with Two Labels')

# 添加图例
plt.legend()

# 显示图形
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pickle

# 生成示例数据
with open('./log/pg10.txt', 'rb') as f:
    y1_values = pickle.load(f)
with open('./log/tf10.txt', 'rb') as f:
    y2_values = pickle.load(f)

# y1_values = [894, 892, 902, 859, 865, 881, 892, 845, 866, 869, 885, 898, 891, 887, 880, 882, 879, 876, 825, 816, 878, 872, 875, 861, 870, 870, 871, 861, 904, 883, 889, 872, 880, 872, 889, 883, 904, 861, 871, 870]

# y2_values = [990, 561, 533, 517, 1019, 561, 1026, 568, 541, 978, 552, 567, 1008, 428, 1013, 525, 513, 516, 483, 1448, 539, 530, 432, 946, 1441, 499, 2623, 980, 1000, 488, 620, 507, 947, 505, 620, 488, 1000, 980, 2623, 499]
num_data_points = len(y1_values)
x_labels = range(0, len(y1_values), 1)

# 设置图形大小
plt.figure(figsize=(30, 5))

# 绘制折线图，设置线的透明度为50%
plt.plot(x_labels, y1_values, label='pg', alpha=0.5)
plt.plot(x_labels, y2_values, label='tf', alpha=0.5)

# 设置坐标轴标签和标题
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Line Chart with Two Labels')

# 设置 x 轴刻度和标签
plt.xticks(rotation=45, ha='right')

# 添加图例
plt.legend(fontsize='large')

# 显示图形
plt.show()
print(len(y1_values))

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pickle

# 生成示例数据
with open('./log/pg1.txt', 'rb') as f:
    y1_values = pickle.load(f)
with open('./log/tf1.txt', 'rb') as f:
    y2_values = pickle.load(f)

num_data_points = len(y1_values)
x_labels =  ['1a', '1b', '1c', '1d', '2a', '2b', '2c', '2d', '3a', '3b', '3c', '4a',
             '4b', '4c', '5a', '5b', '5c', '6a', '6b', '6c', '6d', '6e', '6f', '7a', 
             '7b', '7c', '8a', '8b', '8c', '8d', '9a', '9b', '9c', '9d', '10a', '10b', 
             '10c', '11a', '11b', '11c', '11d', '12a', '12b', '12c', '13a', '13b', '13c', 
             '13d', '14a', '14b', '14c', '15a', '15b', '15c', '15d', '16a', '16b', '16c',
             '16d', '17a', '17b', '17c', '17d', '17e', '17f', '18a', '18b', '18c', '19a',
             '19b', '19c', '19d', '20a', '20b', '20c', '21a', '21b', '21c', '22a', '22b']

# 设置图形大小
plt.figure(figsize=(20, 5))

# 绘制柱状图
bar_width = 0.4
bar_positions1 = np.arange(len(x_labels))
bar_positions2 = bar_positions1 + bar_width

plt.bar(bar_positions1, y1_values, width=bar_width, label='pg', alpha=0.5)
plt.bar(bar_positions2, y2_values, width=bar_width, label='tf', alpha=0.5)

# 设置坐标轴标签和标题
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Bar Chart with Two Labels')

# 设置 x 轴刻度和标签
plt.xticks(bar_positions1 + bar_width / 2, x_labels, rotation=45, ha='right')

# 添加图例
plt.legend(fontsize='large')

# 显示图形
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pickle

# 生成示例数据
with open('./log/pg5.txt', 'rb') as f:
    y1_values = pickle.load(f)
with open('./log/tf5.txt', 'rb') as f:
    y2_values = pickle.load(f)

num_data_points = len(y1_values)
x_labels =  ['1a', '1b', '1c', '1d', '2a', '2b', '2c', '2d', '3a', '3b', '3c', '4a',
             '4b', '4c', '5a', '5b', '5c', '6a', '6b', '6c', '6d', '6e', '6f', '7a', 
             '7b', '7c', '8a', '8b', '8c', '8d', '9a', '9b', '9c', '9d', '10a', '10b', 
             '10c', '11a', '11b', '11c', '11d', '12a', '12b', '12c', '13a', '13b', '13c', 
             '13d', '14a', '14b', '14c', '15a', '15b', '15c', '15d', '16a', '16b', '16c',
             '16d', '17a', '17b', '17c', '17d', '17e', '17f', '18a', '18b', '18c', '19a',
             '19b', '19c', '19d', '20a', '20b', '20c', '21a', '21b', '21c', '22a', '22b',
             '22c', '22d', '23a', '23b', '23c', '24a', '24b', '25a', '25b', '25c', '26a', 
             '26b', '26c', '27a', '27b', '27c', '28a', '28b', '28c']

# 设置图形大小
plt.figure(figsize=(25, 5))

# 绘制柱状图，设置线的透明度为50%
bar_width = 0.4
bar_positions1 = np.arange(len(x_labels))
bar_positions2 = bar_positions1 + bar_width

plt.bar(bar_positions1, y1_values, width=bar_width, label='pg', alpha=0.5)
plt.bar(bar_positions2, y2_values, width=bar_width, label='tf', alpha=0.5)

# 设置坐标轴标签和标题
plt.xlabel('X-axis')
plt.ylabel('Y-axis (log scale)')
plt.title('Bar Chart with Two Labels (log scale)')

# 设置 x 轴刻度和标签
plt.xticks(bar_positions1 + bar_width / 2, x_labels, rotation=45, ha='right')

# 设置 y 轴为对数刻度
# plt.yscale('log')

# 添加图例
plt.legend(fontsize='large')

# 显示图形
plt.show()


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pickle

# 生成示例数据
with open('./log/pg2.txt', 'rb') as f:
    y1_values = pickle.load(f)
with open('./log/tf2.txt', 'rb') as f:
    y2_values = pickle.load(f)
# with open('./log/tf3.txt', 'rb') as f:
#     y3_values = pickle.load(f)
y3_values = [4197.779, 6310.663, 2685.923, 6786.553]
y3_values += [0] * (len(y2_values) - len(y3_values))
num_data_points = len(y1_values)
x_labels =  ['1a', '1b', '1c', '1d', '2a', '2b', '2c', '2d', '3a', '3b', '3c', '4a',
             '4b', '4c', '5a', '5b', '5c', '6a', '6b', '6c', '6d', '6e', '6f', '7a', 
             '7b', '7c', '8a', '8b', '8c', '8d', '9a', '9b', '9c', '9d', '10a', '10b', 
             '10c', '11a', '11b', '11c', '11d', '12a', '12b', '12c', '13a', '13b', '13c', 
             '13d', '14a', '14b', '14c', '15a', '15b', '15c', '15d', '16a', '16b', '16c',
             '16d', '17a', '17b', '17c', '17d', '17e', '17f', '18a', '18b', '18c', '19a',
             '19b', '19c', '19d', '20a', '20b', '20c', '21a', '21b', '21c', '22a', '22b',
             '22c', '22d', '23a', '23b', '23c', '24a', '24b', '25a', '25b', '25c', '26a', 
             '26b', '26c', '27a', '27b', '27c', '28a', '28b', '28c']

# 设置图形大小
plt.figure(figsize=(15, 5))

# 绘制柱状图，设置线的透明度为50%
bar_width = 0.2
bar_positions1 = np.arange(len(x_labels))
bar_positions2 = bar_positions1 + bar_width
bar_positions3 = bar_positions2 + bar_width

plt.bar(bar_positions1, y1_values, width=bar_width, label='pg', alpha=0.5)
plt.bar(bar_positions2, y2_values, width=bar_width, label='tf_par', alpha=0.5)
plt.bar(bar_positions3, y3_values, width=bar_width, label='tf_no', alpha=0.5)

# 设置坐标轴标签和标题
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Bar Chart with Two Labels (log scale)')

# 设置 x 轴刻度和标签
plt.xticks(bar_positions1 + bar_width / 2, x_labels, rotation=45, ha='right')

# 设置 y 轴为对数刻度
# plt.yscale('log')

# 添加图例
plt.legend(fontsize='large')

# 显示图形
plt.show()


In [ ]:
import pickle

# # 生成示例数据
# with open('./log/pg5.txt', 'rb') as f:
#     a = pickle.load(f)
# with open('./log/tf5.txt', 'rb') as f:
#     b = pickle.load(f)
a = [894, 892, 902, 859, 865, 881, 892, 845, 866, 869, 885, 898, 891, 887, 880, 882, 879, 876, 825, 816, 878, 872, 875, 861, 870, 870, 871, 861, 904, 883, 889, 872, 880, 872, 889, 883, 904, 861, 871, 870]

b = [990, 561, 533, 517, 1019, 561, 1026, 568, 541, 978, 552, 567, 1008, 428, 1013, 525, 513, 516, 483, 1448, 539, 530, 432, 946, 1441, 499, 2623, 980, 1000, 488, 620, 507, 947, 505, 620, 488, 1000, 980, 2623, 499]
# x_labels =  ['1a', '1b', '1c', '1d', '2a', '2b', '2c', '2d', '3a', '3b', '3c', '4a',
#              '4b', '4c', '5a', '5b', '5c', '6a', '6b', '6c', '6d', '6e', '6f', '7a', 
#              '7b', '7c', '8a', '8b', '8c', '8d', '9a', '9b', '9c', '9d', '10a', '10b', 
#              '10c', '11a', '11b', '11c', '11d', '12a', '12b', '12c', '13a', '13b', '13c', 
#              '13d', '14a', '14b', '14c', '15a', '15b', '15c', '15d', '16a', '16b', '16c',
#              '16d', '17a', '17b', '17c', '17d', '17e', '17f', '18a', '18b', '18c', '19a',
#              '19b', '19c', '19d', '20a', '20b', '20c', '21a', '21b', '21c', '22a', '22b',
#              '22c', '22d', '23a', '23b', '23c', '24a', '24b', '25a', '25b', '25c', '26a', 
#              '26b', '26c', '27a', '27b', '27c', '28a', '28b', '28c']
print(len(a))
sum = 0
sum1 = 0
sum2 = 0
sum3 = 0
x = []
for i in range(0, len(a)):
    if(a[i] > b[i]):
        x.append(x_labels[i])
        sum += 1
    sum1 += a[i]
    sum2 += b[i]
    sum3 += 0 if b[i] == b[-1] else b[i]
print(sum)
print(sum1)
print(sum2)
print(sum3)
print(x)



In [ ]:
import torch
a = torch.rand((3,20)) # 720
b = a.view(3,4,5) # 40 18 
c = a.view(3,5,4).transpose(1,2)
print(a)
print(c)
print(b)


In [ ]:
from leon_pl import *
sqls_chunk = load_sql(['8c'])
query_latency2, json_dict = getPG_latency(sqls_chunk[0], ENABLE_LEON=True, timeout_limit=0)
node = postgres.ParsePostgresPlanJson(json_dict)
print(node)

In [ ]:
hint_node = plans_lib.FilterScansOrJoins(node.Copy())
hint_node.info['latency'], json = getPG_latency(sqls_chunk[0], hint_node.hint_str(), ENABLE_LEON=False, timeout_limit=0) # timeout 10s
node1 = postgres.ParsePostgresPlanJson(json)
print(node1)


In [ ]:
print(query_latency2)
print(hint_node.info['latency'])

In [ ]:
import torch
cali_all = torch.tensor([1.111, 1100])
cali_all = random_tensor = 10 * torch.rand(cali_all.shape[0])
def format_scientific_notation(number):
            str_number = "{:e}".format(number)
            mantissa, exponent = str_number.split('e')
            mantissa = 9.994 if float(mantissa) >= 9.995 else float(mantissa)
            mantissa = format(mantissa, '.2f')
            exponent = int(exponent)
            exponent = max(-9, min(9, exponent))
            result = "{},{},{:d}".format(mantissa, '1' if exponent >= 0 else '0', abs(exponent))
            return result
cali_str = [format_scientific_notation(i) for i in cali_all.tolist()]
print(cali_str)


In [ ]:
import re


# 示例用法
import os

folder_path = 'job'  # 请根据实际文件夹路径进行设置
a =[]
# 获取文件夹中的所有文件
files = os.listdir(folder_path)

# 遍历每个文件并处理
for file_name in files:
    file_path = os.path.join(folder_path, file_name)

    # 判断是否为文件
    if os.path.isfile(file_path):
        with open(file_path, 'r') as file:
            # 读取文件内容
            content = file.read()
            from_where_content = re.search('FROM(.*)WHERE', content.replace("\n", "")).group(1)

            # 提取别名
            aliases = re.findall(r'AS (\w+)', from_where_content)

            aliases = ",".join(sorted(aliases))
            a.append(aliases)

print(a)  # 输出: ['ct', 'it', 'mc', 'mi_idx', 't']

print("处理完成")

In [ ]:
import pickle
with open('./log/exp_v4.pkl', 'rb') as f:
    exp = pickle.load(f)

In [ ]:
sql = None
sum = 0
for plan in exp['chn,ci,cn,ct,mc,rt,t']:
    node = plan[0]
    if node.info['sql_str'] != sql:
        sql = node.info['sql_str']
        sum += 1
    print(sum)
    print(node.info['latency'])
    print(node.cost)

In [ ]:
import pickle
import os
from pympler import asizeof
import gc
from enum import Enum
i = 0
while True:
    print(i)
    i += 1
    with open('./log/exp_v4.pkl', 'rb') as f:
        exp = pickle.load(f)
    del exp
    gc.collect()




In [ ]:
class FeatureType(Enum):
    numeric = "numeric"
    categorical = "categorical"

    def __str__(self):
        return self.value


In [ ]:

total_size = asizeof.asizeof(exp['an,chn,ci,cn,it,mc,mi,n,rt,t'])

# 将字节数转换为 MB
total_size_in_mb = total_size / (1024.0 ** 2)

# 打印结果
print(f"The total size of my_dict and its references is approximately: {total_size_in_mb:.2f} MB")


In [ ]:
first_elements = [sublist[1] for sublist in exp['an,chn,ci,cn,it,mc,mi,n,rt,t']]
first_elements[0].shape
memory_size_bytes = first_elements[0].element_size() * first_elements[0].numel()

# 将字节数转换为 MB
memory_size_mb = memory_size_bytes / (1024.0 ** 2)

# 打印结果
print(f"The memory size of the tensor is approximately: {memory_size_mb:.2f} MB")


In [ ]:
from pympler import muppy, summary
all_objects = muppy.get_objects()
sum1 = summary.summarize(all_objects)# Prints out a summary of the large objects
summary.print_(sum1)

In [ ]:
import numpy as np
import json
def get_statistic(exp):
    plans = exp

    # get statistics
    db_plans = {}
    db_max_node_len = 0
    runtimes = []
    cards = []
    costs = []

    # get all node types, including subplan, implement by dfs
    node_types = set()
    for eq in exp.keys():
        for plan in exp[eq]:
            plan = plan[0]
            try:
                runtimes.append(plan.info['latency'])
            except:
                pass
            costs.append(plan.cost)
            cards.append(0)
            node_types.add(plan.node_type)
            stack = [plan]
            node_len = 1
            while len(stack) > 0:
                node = stack.pop()
                for child in node.children:
                    node_len += 1
                    node_types.add(child.node_type)
                    stack.append(child)
                    try:
                        runtimes.append(child.info['latency'])
                    except:
                        pass
                    
                    costs.append(child.cost)
                    cards.append(0)
            db_max_node_len = max(db_max_node_len, node_len)
    print(db_max_node_len)

    runtimes, cards, costs = np.array(runtimes), np.array(cards), np.array(costs)

    # write to a json file
    node_types = list(node_types)
    statistics = {
        "Actual Total Time": {
            "type": str(FeatureType.numeric),
            "max": float(np.max(runtimes)),
            "min": float(np.min(runtimes)),
            "center": float(np.median(runtimes)),
            "scale": float(np.quantile(runtimes, 0.75))
            - float(np.quantile(runtimes, 0.25)),
        },
        "Plan Rows": {
            "type": str(FeatureType.numeric),
            "max": float(np.max(cards)),
            "min": float(np.min(cards)),
            "center": float(np.median(cards)),
            "scale": float(np.quantile(cards, 0.75)) - float(np.quantile(cards, 0.25)),
        },
        "Total Cost": {
            "type": str(FeatureType.numeric),
            "max": float(np.max(costs)),
            "min": float(np.min(costs)),
            "center": float(np.median(costs)),
            "scale": float(np.quantile(costs, 0.75)) - float(np.quantile(costs, 0.25)),
        },
        "node_types": {
            "type": str(FeatureType.categorical),
            "value_dict": {node_type: i for i, node_type in enumerate(node_types)},
        },
    }
    return statistics

statistics = get_statistic(exp)
with open(os.getcwd() + '/statistics1.json', "w") as f:
    json.dump(statistics, f)

In [ ]:
join_id='1,2,3,4,5,6'
len(join_id.split(','))


In [ ]:
import torch
import torch.nn as nn

# 假设输入张量 x 的形状为 512 * 40 * node_length
x = torch.rand((512, 40, 18))

# 将 x 展平成二维张量
# x = x.view(-1, 18)

# 定义 nn.Sequential
mlp = nn.Sequential(
    nn.Linear(18, 32),
    nn.ReLU(),  # 假设你的激活函数是 ReLU
    nn.Linear(32, 64),
    nn.ReLU(),
    nn.Linear(64, 32)
)

# 将 x_flattened 输入到 MLP 中
output = mlp(x)

# 输出的形状为 20480 * 32，即 (512 * 40) * 32
print(output.shape)

In [ ]:
from dataclasses import dataclass, field
from typing import List

@dataclass
class EqSetInfo:
    first_latency: float = 90000.0
    current_latency: float = 90000.0
    opt_time: float = 0.0
    query_ids: List[str] = field(default_factory=list)

# 示例数据
all_set = [(1, EqSetInfo(query_ids=['1a', '2a'], opt_time=0.0)),
           (2, EqSetInfo(query_ids=['3a', '4a'], opt_time=10.0)),
           (3, EqSetInfo(query_ids=['5a', '6a'], opt_time=-5.0)),
           (4, EqSetInfo(query_ids=['5a', '6a'], opt_time=0.0)),
           (5, EqSetInfo(query_ids=['2a', '6a'], opt_time=5.0)),
           (6, EqSetInfo(query_ids=['5a', '6a'], opt_time=0.0)),
           (7, EqSetInfo(query_ids=['5a', '6a'], opt_time=-5.0)),
           (8, EqSetInfo(query_ids=['5a', '6a'], opt_time=0.0))]

sql_id = ['1a']

# 过滤条件
updated_set = [item for item in all_set if not (any(x in sql_id for x in item[1].query_ids) or item[1].opt_time==0)]

# 打印结果
for item in updated_set:
    print(item[0], item[1])

In [ ]:
import torch

# 创建一个1400x720的tensor，默认使用float32数据类型
tensor_var = torch.zeros(1400, 720)

# 获取tensor的数据类型
dtype = tensor_var.dtype

# 获取tensor的元素个数
num_elements = tensor_var.numel()

# 计算内存占用
memory_size_bytes = num_elements * dtype.itemsize

# 将字节数转换为兆字节
memory_size_mb = memory_size_bytes / (1024 ** 2)

print(f"Tensor size: {memory_size_mb:.2f} MB")

In [ ]:
import re

def fix_json_msg(json):
    # pattern_any = r'ANY \((.*?):text\[\]\)'
    pattern_all = r'(ANY|ALL) \((.*?):text\[\]\)'

    # matches_any = re.findall(pattern_any, json)
    matches_all = re.findall(pattern_all, json)

    # for match in matches_any:
    #     extracted_string = match
    #     cleaned_string = extracted_string.replace('"', '')
    #     json = json.replace(f'ANY ({extracted_string}):text[]', cleaned_string)
    
    for match_type, match in matches_all:
        extracted_string = match
        cleaned_string = extracted_string.replace('"', '')
        json = json.replace(extracted_string, cleaned_string)

    return json

json_data = '"Base Restrict Info": "((mi.info)::text <> ALL (\'{MET:,UK,Color,\"Black and White\"}\'::text[]))" '
fixed_json = fix_json_msg(json_data)
print(fixed_json)

In [ ]:
import pickle

def save_list_to_disk(file_path, data):
    with open(file_path, 'ab') as file:
        pickle.dump(data, file)

def data_generator(file_path, batch_size=1000):
    with open(file_path, 'rb') as file:
        try:
            while True:
                batch = []
                for _ in range(batch_size):
                    try:
                        item = pickle.load(file)
                        batch.append(item)
                    except EOFError:
                        break
                
                if not batch:
                    break
                
                yield batch
        except EOFError:
            pass

def process_batch(batch):
    # 在这里对批次进行处理，这里简单地打印每个元素
    print(batch)
    # for item in batch:
    #     print(item)

# 生成示例数据
large_list = list(range(999))
for i in range(1000):
    save_list_to_disk('large_list.pkl', [i])

# 使用生成器逐批次读取和处理数据
file_path = 'large_list.pkl'
generator = data_generator(file_path, batch_size=100)
print(generator)
# for batch in generator:
#     # print(len(batch[0]))
#     process_batch(batch)

In [ ]:
import torch
import gc
# 创建 PyTorch 张量
def fun():
    a = torch.randn((90000, 1000, 27), device='cuda:3')

# 删除张量
# del a
fun()
# 清空 GPU 缓存
# torch.cuda.empty_cache()

In [ ]:
indexes_list = [torch.randint(0, 10, (y, 1)) for y in range(5, 8)]
indexes_list[1].shape

In [1]:
import pickle
import torch
from util import envs, plans_lib, treeconv, encoding
with open('./log/exp_v4.pkl', 'rb') as f:
    exp = pickle.load(f)
model = torch.load('./log/model.pth')
workload = envs.wordload_init('job')
nodeFeaturizer = plans_lib.TreeNodeFeaturizer_V2(workload.workload_info)
exp.keys()

/data1/wyz/miniconda3/envs/leon/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-01-10 08:35:04,793	INFO util.py:159 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.


Read Workload: job


dict_keys(['chn,ci,cn,ct,mc,rt,t', 'at,cn,ct,it1,k,mc,mi,mk,t', 'ct,it,mc,mi_idx,t', 'cn,ct,it1,it2,mc,mi,mi_idx,t', 'an1,ci,cn,mc,n1,rt,t', 'ci,k,mk,n,t', 'cn,ct,it1,it2,k,kt,mc,mi,mi_idx,mk,t', 'cc,cct1,cct2,ci,it1,it2,k,mi,mi_idx,mk,n,t', 'it1,it2,k,kt,mi,mi_idx,mk,t', 'cn,ct,it,it2,kt,mc,mi,miidx,t', 'cn,ct,k,lt,mc,mi,mk,ml,t', 'cn,ct,k,lt,mc,mk,ml,t', 'cc,cct1,cct2,cn,ct,k,lt,mc,mi,mk,ml,t', 'an,chn,ci,cn,it,k,mc,mi,mk,n,rt,t', 'an,ci,it,lt,ml,n,pi,t', 'an,cc,cct1,cct2,chn,ci,cn,it,it3,k,mc,mi,mk,n,pi,rt,t', 'k,lt,mk,ml,t1,t2', 'cn,k,mc,mk,t', 'cc,cct1,cct2,chn,ci,it2,k,kt,mi_idx,mk,n,t', 'cc,cct1,cn,ct,it1,k,kt,mc,mi,mk,t', 'cc,cct1,cct2,chn,ci,k,kt,mk,n,t', 'ct,it,mc,mi,t', 'a1,ci,cn,mc,n1,rt,t', 'an,chn,ci,cn,it,mc,mi,n,rt,t', 'an,ci,cn,mc,n,rt,t', 'cc,cct1,cct2,cn,ct,it1,it2,k,kt,mc,mi,mi_idx,mk,t', 'it,k,mi_idx,mk,t', 'aka_t,cn,ct,it1,k,mc,mi,mk,t', 'ci,cn,k,mc,mk,n,t', 'an,chn,ci,cn,mc,n,rt,t', 'k,mi,mk,t', 'ci,it1,it2,mi,mi_idx,n,t', 'cn1,cn2,it1,it2,kt1,kt2,lt,mc1,mc2,mi_i

In [8]:
model = torch.load('./log/model.pth')

In [10]:
with open('./log/exp_v4.pkl', 'rb') as f:
    exp = pickle.load(f)

In [12]:
import torch



num = 0
dict1 = dict()
# for i, plan in enumerate(exp['k,lt,mk,ml,t1,t2']): # 32b
# for i, plan in enumerate(exp['an1,ci,cn,mc,n1,rt,t']): # 8d
for i, plan in enumerate(exp['cc,cct1,cct2,ci,it1,it2,k,mi,mi_idx,mk,n,t']): # 10c

    node = plan[0]
    if node.info['sql_str'] not in dict1.keys():
        num += 1
        dict1[node.info['sql_str']] = num
    # if dict1[node.info['sql_str']] == 2:
    print(i)
    # print(node.info['sql_str'])
    print("sql", dict1[node.info['sql_str']])
    print("index", node.info['index'])
    print(node.cost)
    hint_node = plans_lib.FilterScansOrJoins(node.Copy())
    # print(hint_node.hint_str())
    # print(node)
    # print(node.info['query_feature'])
    print(node.info['latency'])
        ####
    model.eval()
    null_node = plans_lib.Binarize(node)
    trees, indexes = encoding.TreeConvFeaturize(nodeFeaturizer, [null_node], 200)
    cali = torch.tanh(model(node.info['query_feature'].unsqueeze(0), trees, indexes)).add(1).squeeze(1)
    print(cali)
    print(cali * torch.log(torch.tensor([node.cost])))

# for j,i in enumerate(dict1.keys()):
#     print(j+1, i)

0
sql 1
index 4869
11895.399966
3056.893
tensor([0.0456], grad_fn=<SqueezeBackward1>)
tensor([0.4276], grad_fn=<MulBackward0>)
1
sql 1
index 4925
20755280318.07862
1000000
tensor([1.5188], grad_fn=<SqueezeBackward1>)
tensor([36.0810], grad_fn=<MulBackward0>)
2
sql 1
index 4923
6312988773.722534
1000000
tensor([1.6824], grad_fn=<SqueezeBackward1>)
tensor([37.9645], grad_fn=<MulBackward0>)
3
sql 1
index 4921
148387350.10089
1000000
tensor([1.7360], grad_fn=<SqueezeBackward1>)
tensor([32.6640], grad_fn=<MulBackward0>)
4
sql 1
index 4902
83689258.022945
1000000
tensor([1.9967], grad_fn=<SqueezeBackward1>)
tensor([36.4242], grad_fn=<MulBackward0>)
5
sql 1
index 4898
83654121.3864
1000000
tensor([1.9851], grad_fn=<SqueezeBackward1>)
tensor([36.2131], grad_fn=<MulBackward0>)
6
sql 1
index 4919
83653617.72465
1000000
tensor([1.7948], grad_fn=<SqueezeBackward1>)
tensor([32.7418], grad_fn=<MulBackward0>)
7
sql 1
index 4914
56971535.552618
1000000
tensor([1.7676], grad_fn=<SqueezeBackward1>)
tens

In [12]:
import pickle

with open('./error.pkl', 'rb') as f:
    message = pickle.load(f)
for j,i in enumerate(message):
    # if float(i['Plan']['Total Cost']) == 84058.53:
    #     print("yes")
    print(j,float(i['Plan']['Total Cost']))
    if j== 155:
        print(i)

0 5080.347275
1 5080.314775
2 5079.609497
3 5080.319775
4 199003.346644
5 199002.641366
6 199003.351644
7 199003.364144
8 199014.516644
9 5080.3174
10 5080.347275
11 5080.314775
12 5080.319775
13 5091.482275
14 5091.487275
15 5091.499775
16 199014.519144
17 5080.328525
18 5080.344775
19 5080.312275
20 5078.06981
21 5080.317275
22 1112142.885839
23 1112140.643374
24 1112142.890839
25 1112142.903339
26 1112154.595839
27 5080.3149
28 5080.344775
29 5080.312275
30 5080.317275
31 5092.019775
32 5092.024775
33 5092.037275
34 1112154.598339
35 5080.326025
36 5080.344775
37 5080.312275
38 5078.069839
39 5080.317275
40 68595.999112
41 68593.756676
42 68596.004112
43 68596.016612
44 68607.709112
45 5080.3149
46 5080.344775
47 5080.312275
48 5080.317275
49 5092.019775
50 5092.024775
51 5092.037275
52 68607.711612
53 5080.326025
54 31888.114087
55 31888.091587
56 29262.396865
57 31888.101587
58 282197.203131
59 279571.50841
60 282197.213131
61 282197.210631
62 284385.861192
63 31888.094212
64 3188

In [15]:
import sqlparse
sql = "SELECT mi.info,mi_idx.info,n.name,t.title FROM   info_type AS it2, keyword AS k, movie_keyword AS mk, movie_info_idx AS mi_idx, complete_cast AS cc, comp_cast_type AS cct1, comp_cast_type AS cct2, cast_info AS ci, movie_info AS mi, info_type AS it1, name AS n, title AS t  WHERE cct1.id = cc.subject_id AND cct2.id = cc.status_id AND ci.movie_id = cc.movie_id AND ci.movie_id = mi.movie_id AND ci.movie_id = mi_idx.movie_id AND ci.movie_id = mk.movie_id AND it1.id = mi.info_type_id AND it2.id = mi_idx.info_type_id AND k.id = mk.keyword_id AND mi.movie_id = cc.movie_id AND mi.movie_id = mi_idx.movie_id AND mi.movie_id = mk.movie_id AND mi_idx.movie_id = cc.movie_id AND mi_idx.movie_id = mk.movie_id AND mk.movie_id = cc.movie_id AND n.id = ci.person_id AND t.id = cc.movie_id AND t.id = ci.movie_id AND t.id = mi.movie_id AND t.id = mi_idx.movie_id AND t.id = mk.movie_id AND ((cct1.kind)::text = ANY ('{cast,crew}'::text[])) AND ((cct2.kind)::text = 'complete+verified'::text) AND ((ci.note)::text = ANY ('{(writer),(head writer),(written by),(story),(story editor)}'::text[])) AND ((it1.info)::text = 'genres'::text) AND ((it2.info)::text = 'votes'::text) AND ((k.keyword)::text = ANY ('{murder,violence,blood,gore ,death,female-nudity,hospital}'::text[])) AND ((mi.info)::text = ANY ('{Horror,Thriller}'::text[])) AND ((n.gender)::text = 'm'::text) AND (t.production_year > 2000);"
sql = sqlparse.format(sql, reindent=True, keyword_case="upper")
print(sql)

SELECT mi.info,
       mi_idx.info,
       n.name,
       t.title
FROM info_type AS it2,
     keyword AS k,
     movie_keyword AS mk,
     movie_info_idx AS mi_idx,
     complete_cast AS cc,
     comp_cast_type AS cct1,
     comp_cast_type AS cct2,
     cast_info AS ci,
     movie_info AS mi,
     info_type AS it1,
     name AS n,
     title AS t
WHERE cct1.id = cc.subject_id
  AND cct2.id = cc.status_id
  AND ci.movie_id = cc.movie_id
  AND ci.movie_id = mi.movie_id
  AND ci.movie_id = mi_idx.movie_id
  AND ci.movie_id = mk.movie_id
  AND it1.id = mi.info_type_id
  AND it2.id = mi_idx.info_type_id
  AND k.id = mk.keyword_id
  AND mi.movie_id = cc.movie_id
  AND mi.movie_id = mi_idx.movie_id
  AND mi.movie_id = mk.movie_id
  AND mi_idx.movie_id = cc.movie_id
  AND mi_idx.movie_id = mk.movie_id
  AND mk.movie_id = cc.movie_id
  AND n.id = ci.person_id
  AND t.id = cc.movie_id
  AND t.id = ci.movie_id
  AND t.id = mi.movie_id
  AND t.id = mi_idx.movie_id
  AND t.id = mk.movie_id
  AND ((

In [16]:
import sqlparse
sql = "SELECT mi.info,mi_idx.info,n.name,t.title   FROM   comp_cast_type AS cct2, info_type AS it2, keyword AS k, movie_keyword AS mk, movie_info_idx AS mi_idx, complete_cast AS cc, comp_cast_type AS cct1, cast_info AS ci, movie_info AS mi, info_type AS it1, name AS n, title AS t  WHERE cct1.id = cc.subject_id AND cct2.id = cc.status_id AND ci.movie_id = cc.movie_id AND ci.movie_id = mi.movie_id AND ci.movie_id = mi_idx.movie_id AND ci.movie_id = mk.movie_id AND it1.id = mi.info_type_id AND it2.id = mi_idx.info_type_id AND k.id = mk.keyword_id AND mi.movie_id = cc.movie_id AND mi.movie_id = mi_idx.movie_id AND mi.movie_id = mk.movie_id AND mi_idx.movie_id = cc.movie_id AND mi_idx.movie_id = mk.movie_id AND mk.movie_id = cc.movie_id AND n.id = ci.person_id AND t.id = cc.movie_id AND t.id = ci.movie_id AND t.id = mi.movie_id AND t.id = mi_idx.movie_id AND t.id = mk.movie_id AND ((cct1.kind)::text = ANY ('{cast,crew}'::text[])) AND ((cct2.kind)::text = 'complete+verified'::text) AND ((ci.note)::text = ANY ('{(writer),(head writer),(written by),(story),(story editor)}'::text[])) AND ((it1.info)::text = 'genres'::text) AND ((it2.info)::text = 'votes'::text) AND ((k.keyword)::text = ANY ('{murder,violence,blood,gore,death,female-nudity,hospital}'::text[])) AND ((mi.info)::text = ANY ('{Horror,Thriller}'::text[])) AND ((n.gender)::text = 'm'::text) AND (t.production_year > 2000);"
sql = sqlparse.format(sql, reindent=True, keyword_case="upper")
print(sql)

SELECT mi.info,
       mi_idx.info,
       n.name,
       t.title
FROM comp_cast_type AS cct2,
     info_type AS it2,
     keyword AS k,
     movie_keyword AS mk,
     movie_info_idx AS mi_idx,
     complete_cast AS cc,
     comp_cast_type AS cct1,
     cast_info AS ci,
     movie_info AS mi,
     info_type AS it1,
     name AS n,
     title AS t
WHERE cct1.id = cc.subject_id
  AND cct2.id = cc.status_id
  AND ci.movie_id = cc.movie_id
  AND ci.movie_id = mi.movie_id
  AND ci.movie_id = mi_idx.movie_id
  AND ci.movie_id = mk.movie_id
  AND it1.id = mi.info_type_id
  AND it2.id = mi_idx.info_type_id
  AND k.id = mk.keyword_id
  AND mi.movie_id = cc.movie_id
  AND mi.movie_id = mi_idx.movie_id
  AND mi.movie_id = mk.movie_id
  AND mi_idx.movie_id = cc.movie_id
  AND mi_idx.movie_id = mk.movie_id
  AND mk.movie_id = cc.movie_id
  AND n.id = ci.person_id
  AND t.id = cc.movie_id
  AND t.id = ci.movie_id
  AND t.id = mi.movie_id
  AND t.id = mi_idx.movie_id
  AND t.id = mk.movie_id
  AND ((

In [4]:
# 假设 exp1[key] 是一个列表
exp1 = {'key': [1, 2, 3]}
values = [4, 5, 6]

# 使用 extend 方法将 values 中的元素添加到 exp1[key] 列表的末尾
exp1['key'].extend(values)

# 输出修改后的 exp1[key]
print(exp1['key'])

[1, 2, 3, 4, 5, 6]


In [1]:
import torch
from torch import nn
from util import treeconv


class Residual(nn.Module):
    def __init__(self, input_channels, num_channels,
                 use_1x1conv=False, strides=1):
        super().__init__()
        self.conv1 = treeconv.TreeConv1d(input_channels, num_channels,
                                         kernel_size=3, padding=1, stride=strides)
        self.conv2 = treeconv.TreeConv1d(num_channels, num_channels,
                                         kernel_size=3, padding=1)
        if use_1x1conv:
            self.conv3 = treeconv.TreeConv1d(input_channels, num_channels,
                                         kernel_size=1, stride=strides)
        else:
            self.conv3 = None
        self.bn1 = treeconv.TreeStandardize()
        self.bn2 = treeconv.TreeStandardize()
        self.relu1 = treeconv.TreeAct(nn.LeakyReLU())
        self.relu2 = treeconv.TreeAct(nn.LeakyReLU())

    def forward(self, X):
        Y = self.relu1(self.bn1(self.conv1(X)))
        Y = self.bn2(self.conv2(Y))
        if self.conv3:
            X = self.conv3(X)
        Y += X
        return self.relu2(Y)
    
def resnet_block(input_channels, num_channels, num_residuals,
                 first_block=False):
    blk = []
    for i in range(num_residuals):
        if i == 0 and not first_block:
            blk.append(Residual(input_channels, num_channels,
                                use_1x1conv=True, strides=2))
        else:
            blk.append(Residual(num_channels, num_channels))
    return blk



input_size = 50
data = torch.randn(3, 54, input_size)
indexes = torch.randint(0, 5, size=(3, input_size, 1))  # 修正为在 data 尺寸范围内的索引值

b1 = nn.Sequential(treeconv.TreeConv1d(input_size, 64,
                                         kernel_size=3, padding=1, stride=1),
                   treeconv.TreeStandardize(),treeconv.TreeAct(nn.LeakyReLU()),
                   treeconv.TreeMaxPool_With_Kernel_Stride())
b2 = nn.Sequential(*resnet_block(64, 64, 2, first_block=True))
b3 = nn.Sequential(*resnet_block(64, 128, 2))
b4 = nn.Sequential(*resnet_block(128, 256, 2))

# 实例化 TreeConv1d
# tree_conv1d = treeconv.TreeConv1d(in_dims=54, out_dims=128)
net = nn.Sequential(b1, b2, b3, b4, treeconv.TreeAvgPool())
# ,
# net =Residual(54, 128)
# 前向传播
output_feats = net((data, indexes))
# for layer in net:
#     (data, indexes) = layer((data, indexes))
#     print(layer.__class__.__name__,'output shape:\t', (data, indexes).shape)

# 打印尺寸
print("输入尺寸:", data.size())
print("输出尺寸:", output_feats.size())

输入尺寸: torch.Size([3, 54, 50])
输出尺寸: torch.Size([3, 256])


In [11]:
import torch

# 示例输入
trees = torch.randn(2, 3, 4)  # 2个样本，每个样本有3个特征，4个节点

# 计算每个样本每个特征在节点上的平均值
mean_values = trees.max(dim=2).values

print("Input size:", trees.size())
print("Output size:", mean_values.size())
print("Output values:", mean_values)

Input size: torch.Size([2, 3, 4])
Output size: torch.Size([2, 3])
Output values: tensor([[1.5330, 2.2045, 1.5099],
        [1.3790, 0.0403, 1.3384]])


In [9]:
plan = 24.5
def find_actual_total_time(json_dict, tolerance=0.02):
    if 'Total Cost' in json_dict and 'Actual Total Time' in json_dict:
        target_value = round(plan * 100) / 100
        if abs(json_dict['Total Cost'] - target_value) < tolerance:
            return json_dict['Actual Total Time']
    
    if 'Plans' in json_dict:
        for sub_plan in json_dict['Plans']:
            result = find_actual_total_time(sub_plan, tolerance)
            if result is not None:
                return result
    
    return None

# 示例用法
your_json_dict = {
    'Total Cost': 42.0,
    'Actual Total Time': 10.5,
    'Plans': [ {
        'Total Cost': 42.0, 
        'Actual Total Time': 10.0,
        'Plans': [{
        'Total Cost': 2323, 
        'Actual Total Time': 15.0,
        }]
        },
        {
        'Total Cost': 42.0, 
        'Actual Total Time': 10.0,
        'Plans': [{
        'Total Cost': 24.5, 
        'Actual Total Time': 15.0,
        }]
    }]
}

result = find_actual_total_time(your_json_dict)
print(result)

15.0


In [5]:
import json

with open("test.json", 'r') as file:
        data = json.load(file)
        print("成功读取JSON文件:")
        print(data)


成功读取JSON文件:
{'Plan': {'Node Type': 'Nested Loop', 'Parallel Aware': False, 'Async Capable': False, 'Join Type': 'Inner', 'Startup Cost': 10376.59, 'Total Cost': 126417.98, 'Plan Rows': 1, 'Plan Width': 32, 'Actual Startup Time': 463.779, 'Actual Total Time': 3335.55, 'Actual Rows': 6, 'Actual Loops': 1, 'Output': ['n.name', 't.title'], 'Inner Unique': True, 'Plans': [{'Node Type': 'Nested Loop', 'Parent Relationship': 'Outer', 'Parallel Aware': False, 'Async Capable': False, 'Join Type': 'Inner', 'Startup Cost': 10376.46, 'Total Cost': 126417.82, 'Plan Rows': 1, 'Plan Width': 36, 'Actual Startup Time': 463.771, 'Actual Total Time': 3335.512, 'Actual Rows': 6, 'Actual Loops': 1, 'Output': ['n.name', 't.title', 'cc.status_id'], 'Inner Unique': True, 'Plans': [{'Node Type': 'Nested Loop', 'Parent Relationship': 'Outer', 'Parallel Aware': False, 'Async Capable': False, 'Join Type': 'Inner', 'Startup Cost': 10376.32, 'Total Cost': 126417.4, 'Plan Rows': 3, 'Plan Width': 40, 'Actual Startup 

In [11]:
def find_actual_total_time(n):
    if 'Total Cost' in n and 'Actual Total Time' in n:
        print(n['Total Cost'])
        if abs(n['Total Cost'] - round(125993.434362 * 100) / 100.0) < 0.02:
            return n['Actual Total Time']
    
    if 'Plans' in n:
        for sub_plan in n['Plans']:
            result = find_actual_total_time(sub_plan)
            if result is not None:
                return result
    return None
json_dict = data['Plan']
a = find_actual_total_time(json_dict)
print(a)

126417.98
126417.82
126417.4
126407.42
126071.64
125993.43
3327.056


In [6]:
from util import pg_executor
explain_str1 = 'explain(verbose, format json, analyze)'
sql = "SELECT n.name,t.title   FROM   cast_info AS ci, char_name AS chn, comp_cast_type AS cct1, comp_cast_type AS cct2, complete_cast AS cc, keyword AS k, kind_type AS kt, movie_keyword AS mk, name AS n, title AS t  WHERE cct1.id = cc.subject_id AND cct2.id = cc.status_id AND chn.id = ci.person_role_id AND ci.movie_id = cc.movie_id AND k.id = mk.keyword_id AND kt.id = t.kind_id AND mk.movie_id = cc.movie_id AND mk.movie_id = ci.movie_id AND n.id = ci.person_id AND t.id = cc.movie_id AND t.id = ci.movie_id AND t.id = mk.movie_id AND ((cct1.kind)::text = 'cast'::text) AND ((cct2.kind)::text ~~ '%e%'::text) AND ((k.keyword)::text = ANY ('{black-male-white-female-relationship,reference-to-burt-reynolds,punch-card,number-69,christmas-card,development}'::text[])) AND ((kt.kind)::text = 'episode'::text) AND (chn.name IS NOT NULL) AND (((chn.name)::text ~~ '%man%'::text) OR ((chn.name)::text ~~ '%Man%'::text)) AND (t.production_year > 1985);"
s1 = str(explain_str1).rstrip() + '\n' + sql
with pg_executor.MyCursor(1120) as cursor:
    cursor.execute('SET enable_leon=on;')
    cursor.execute(f"set leon_port={9999};")
    cursor.execute(f"SET leon_query_name='picknode:{'ci,k,mk,n,t'};{125993.434362}';") # 第0个plan 0 
    result = pg_executor.Execute(s1, True, True, 0, cursor).result
json_dict = result[0][0][0]['Plan']


In [7]:
print(json_dict)
def find_actual_total_time(n):
    if 'Total Cost' in n and 'Actual Total Time' in n:
        print(n['Total Cost'])
        if abs(n['Total Cost'] - round(125993.434362 * 100) / 100.0) < 0.02:
            return n['Actual Total Time']
    
    if 'Plans' in n:
        for sub_plan in n['Plans']:
            result = find_actual_total_time(sub_plan)
            if result is not None:
                return result
    return None
a = find_actual_total_time(json_dict)
print(a)

{'Node Type': 'Nested Loop', 'Parallel Aware': False, 'Async Capable': False, 'Join Type': 'Inner', 'Startup Cost': 10376.59, 'Total Cost': 126417.98, 'Plan Rows': 1, 'Plan Width': 32, 'Actual Startup Time': 300.109, 'Actual Total Time': 1900.094, 'Actual Rows': 6, 'Actual Loops': 1, 'Output': ['n.name', 't.title'], 'Inner Unique': True, 'Plans': [{'Node Type': 'Nested Loop', 'Parent Relationship': 'Outer', 'Parallel Aware': False, 'Async Capable': False, 'Join Type': 'Inner', 'Startup Cost': 10376.46, 'Total Cost': 126417.82, 'Plan Rows': 1, 'Plan Width': 36, 'Actual Startup Time': 300.1, 'Actual Total Time': 1900.064, 'Actual Rows': 6, 'Actual Loops': 1, 'Output': ['n.name', 't.title', 'cc.status_id'], 'Inner Unique': True, 'Plans': [{'Node Type': 'Nested Loop', 'Parent Relationship': 'Outer', 'Parallel Aware': False, 'Async Capable': False, 'Join Type': 'Inner', 'Startup Cost': 10376.32, 'Total Cost': 126417.4, 'Plan Rows': 3, 'Plan Width': 40, 'Actual Startup Time': 300.079, 'Actua

In [1]:
import pickle
with open('./log/exp_v5.pkl', 'rb') as f:
    exp = pickle.load(f)

In [2]:
num = 0
dict1 = dict()
for i, plan in enumerate(exp['an,chn,ci,cn,mc,n,rt,t']):

    node = plan[0]
    if node.info['sql_str'] not in dict1.keys():
        num += 1
        dict1[node.info['sql_str']] = num
    # if dict1[node.info['sql_str']] == 2:
    print(i)
    print(node.info['sql_str'])
    print("sql", dict1[node.info['sql_str']])
    print("latency", node.info['latency'])
    print(node.cost)

0
SELECT an.id,an.imdb_index,an.md5sum,an.name,an.name_pcode_cf,an.name_pcode_nf,an.person_id,an.surname_pcode,chn.id,chn.imdb_id,chn.imdb_index,chn.md5sum,chn.name,chn.name_pcode_nf,chn.surname_pcode,ci.id,ci.movie_id,ci.note,ci.nr_order,ci.person_id,ci.person_role_id,ci.role_id,cn.country_code,cn.id,cn.imdb_id,cn.md5sum,cn.name,cn.name_pcode_nf,cn.name_pcode_sf,mc.company_id,mc.company_type_id,mc.id,mc.movie_id,mc.note,n.gender,n.id,n.imdb_id,n.imdb_index,n.md5sum,n.name,n.name_pcode_cf,n.name_pcode_nf,n.surname_pcode,rt.id,rt.role,t.episode_nr,t.episode_of_id,t.id,t.imdb_id,t.imdb_index,t.kind_id,t.md5sum,t.phonetic_code,t.production_year,t.season_nr,t.series_years,t.title   FROM   aka_name AS an, cast_info AS ci, char_name AS chn, company_name AS cn, movie_companies AS mc, name AS n, role_type AS rt, title AS t  WHERE an.person_id = ci.person_id AND an.person_id = n.id AND chn.id = ci.person_role_id AND ci.movie_id = mc.movie_id AND ci.movie_id = t.id AND ci.person_id = n.id AND ci

In [3]:
keys1 = exp.keys()
for key in keys1:
    for plan in exp[key]:
        if plan[0].info['latency'] < 100:
            print(plan[0].info['latency'])

23.806
22.51
23.044
51.541
22.729
30.064
22.057
24.126
29.59
24.698
30.849
23.377
33.032
25.599
23.864
22.48
25.821
27.273
33.406
63.883
54.568
67.486
19.761
16.755
19.326
73.144
60.659
95.551
45.226
42.98
66.521
22.279
21.869
49.812
33.68
19.857
21.039
21.257
29.44
37.92
55.857
22.967
21.948
23.377
52.727
25.076
36.803
83.937
22.292
22.929
29.632
72.635
51.656
20.888
38.568
25.178
25.702
24.235
28.431
24.772
27.747
24.223
29.565
28.101
26.603
26.204
21.017
23.828
25.509
26.924
45.499
22.265
33.103
29.513
27.988
52.19
23.723
22.544
26.413
24.5
24.363
44.673
39.952
30.565
27.002
22.122
75.327
75.825
62.776
65.356
19.803
46.998
43.988
25.384
44.308
43.012
40.517
32.656
23.422
20.063
19.922
70.473
50.091
66.775
60.987
42.174
57.14
61.183
47.532
49.559
40.948
47.443
49.618
48.48
58.884
47.003
45.35
45.765
57.119
71.68
56.85
61.422
75.741
55.537
63.675
52.325
63.534
82.406
82.591
87.483
66.639
40.862
81.792
27.445
72.103
21.801
27.218
28.765
49.179
49.671
46.974
63.299
24.866
99.521
46.276


In [20]:
import torch
# def diff_normalized(self, p1, p2):
#         norm = torch.sum(p1, dim=1)
#         pair = (p1 - p2) / norm
#         return pair
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)
norm = torch.sum(a, dim=1)

print(norm)
pair = (a - b) / norm.unsqueeze(1)
print(a-b)
print(pair.dtype)
labels = torch.tensor([0, 1, 0, 1])

# 将标签转为 one-hot 编码
one_hot_labels = torch.nn.functional.one_hot(labels)

# 打印结果
print(one_hot_labels.dtype)
target = torch.randn(3, 5).softmax(dim=1)
print(target)

tensor([[0.2321, 0.2035, 0.3909],
        [0.1782, 0.7385, 0.6028]])
tensor([[0.1153, 0.5044, 0.9241],
        [0.1284, 0.3408, 0.9792]])
tensor([0.8265, 1.5195])
tensor([[ 0.1168, -0.3009, -0.5332],
        [ 0.0498,  0.3978, -0.3764]])
torch.float32
torch.int64
tensor([[0.0196, 0.1322, 0.3457, 0.2163, 0.2861],
        [0.4188, 0.2992, 0.0171, 0.1750, 0.0898],
        [0.0708, 0.0811, 0.6032, 0.0698, 0.1751]])
